### ISSUE TITLE
请问您的这个项目主要优化或者说特性？

### ISSUE THREAD

**Issue by ghost** [KFERMercer/OpenWrt#1]
对比Lean的有什么特别的地方吗？

**Comment by KFERMercer** [comment]
基本上是基于Lean的源, 最**明显**的变化就是加了一些软件包. 

但最大的不同是一些针对我个人习惯的修改, 这部分的更改太细碎难以概括, 有兴趣的话欢迎查阅[commit log](https://github.com/KFERMercer/OpenWrt/commits?author=KFERMercer).
