### ISSUE TITLE
一串fatal  log

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#11]
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..1277354329d4a67e4852e10662ac9a9303227bd7
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..1277354329d4a67e4852e10662ac9a9303227bd7

**Comment by KFERMercer** [comment]
actions只会加载最新版, 不需要理会
