### ISSUE TITLE
新建容器报错

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#16]
cannot unmarshal array into Go struct field HostConfig.HostConfig.LogConfig of type container.LogConfig

**Comment by tcsr200722** [comment]
大佬,帮忙更新一下dockerman这个插件,新版已经解决了这个错误

**Comment by KFERMercer** [comment]
能不能提供下 dockerman 关于修复这个问题的具体提交链接?

**Comment by tcsr200722** [comment]
https://github.com/lisaac/luci-app-dockerman/commit/d400302d3ca32443c7bc12d6176806a8d72265ff



 
---原始邮件---
发件人: "ZhenYu"<notifications@github.com&gt;
发送时间: 2020年4月19日 02:11:36
收件人: "KFERMercer/OpenWrt"<OpenWrt@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tcsr200722"<350524166@qq.com&gt;;
主题: Re: [KFERMercer/OpenWrt] 新建容器报错 (#16)




 
能不能提供下 dockerman 关于修复这个问题的具体提交链接?

**Comment by KFERMercer** [comment]
好的
