### ISSUE TITLE
请问luci-app-smartinfo有哪些依赖需要安装的吗？

### ISSUE THREAD

**Issue by iamaluckyguy** [KFERMercer/OpenWrt#18]
luci-app-smartinfo。每次点启用再确认刷新后还是未启用状态。已经认出了移动硬盘。

请问会是什么原因呢？谢谢！我看了选择这个app后smartmontools是勾选了的。

盼指点一下。谢谢！

**Comment by KFERMercer** [comment]
本来就没有所谓的开启状态, 正常如下图设置即可:
![image](https://user-images.githubusercontent.com/37098748/81605492-1c12de00-9404-11ea-8318-d4b6243d2bce.png)

**Comment by iamaluckyguy** [comment]
谢谢解答。我的刷完就是未启用状态。就是启用那个钩不是能勾选。后来我看了一下日志发现了执行文件和监视脚本无权限。通过chmod +x 这两个文件后解决了。我编译的Lean的lede， 新三D2。有无办法默认就有权限的？是我的编译不对还是程序本身的权限检查引起的？


chmod +x /etc/init.d/smartinfo
chmod +x /usr/lib/smartinfo/smart_status.sh

这样后就像你的图上那样显示了。
=================

Mon May 11 16:57:13 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:18 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:21 2020 daemon.err uhttpd[1460]: env: can't execute '/etc/init.d/smartinfo': Permission denied
Mon May 11 16:57:21 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:23 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: env: can't execute '/etc/init.d/smartinfo': Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /etc/init.d/smartinfo: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /etc/init.d/smartinfo: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /etc/init.d/smartinfo: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: env: can't execute '/etc/init.d/smartinfo': Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /etc/init.d/smartinfo: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /etc/init.d/smartinfo: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /etc/init.d/smartinfo: Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: env: can't execute '/etc/init.d/smartinfo': Permission denied
Mon May 11 16:57:24 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:28 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:29 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 16:57:33 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied


Mon May 11 17:00:03 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 17:00:08 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 17:00:11 2020 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED f0:c3:71:75:d0:da
Mon May 11 17:00:11 2020 daemon.info hostapd: wlan0: STA f0:c3:71:75:d0:da IEEE 802.11: disassociated due to inactivity
Mon May 11 17:00:12 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 17:00:12 2020 daemon.info hostapd: wlan0: STA f0:c3:71:75:d0:da IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Mon May 11 17:00:13 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 17:00:17 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 17:00:18 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied
Mon May 11 17:00:21 2020 daemon.err uhttpd[1460]: killall: smart_checker.sh: no process killed
Mon May 11 17:00:21 2020 daemon.err uhttpd[1460]: killall: smart_checker.sh: no process killed
Mon May 11 17:00:21 2020 daemon.err uhttpd[1460]: sh: /usr/lib/smartinfo/smart_status.sh: Permission denied

**Comment by KFERMercer** [comment]
你确定编译时是用的我库里的smartinfo吗?

**Comment by iamaluckyguy** [comment]
你好。我不知道如何只git你的这个单独包到我的编译，所以我直接下载了你的完整包。再传到我的git的。这样是否OK？https://github.com/iamaluckyguy/luci-app-smartinfo
谢谢！或者你能指点一下如何编译的时候只单独包含你的这个包？貌似要下载你的所有package。

**Comment by iamaluckyguy** [comment]
我在这个文件里面加入clone我的这个包的：https://github.com/iamaluckyguy/Actions-Lean-OpenWrt-NewWIFI3/blob/master/.github/workflows/build-openwrt-lucky.yml


----------------------

    - name: Clone Smartinfo
      run: git clone https://github.com/iamaluckyguy/luci-app-smartinfo.git openwrt/package/lucky/luci-app-smartinfo

**Comment by KFERMercer** [comment]
直接复制我库里的版本
