### ISSUE TITLE
20200703编译出错

### ISSUE THREAD

**Issue by flyhigao** [KFERMercer/OpenWrt#20]
make defconfig最后提示：
WARNING: Makefile 'package/feeds/luci/luci-app-wol/Makefile' has a dependency on 'wol', which does not exist

导致make时失败（你的action中也失败了）

临时解决方法：
package/feeds/luci/luci-app-wol/Makefile #这个文件要去掉wol
-LUCI_DEPENDS:=+etherwake +wol
+LUCI_DEPENDS:=+etherwake

**Comment by KFERMercer** [comment]
修复.
