### ISSUE TITLE
老哥您看。Github提示很快master将要不可用了，官方建议改为main了......

### ISSUE THREAD

**Issue by ghost** [KFERMercer/OpenWrt#22]
![图片](https://user-images.githubusercontent.com/67452171/88445014-98895a80-ce52-11ea-8996-8e3cd039280c.png)

**Comment by KFERMercer** [comment]
wtf

**Comment by ghost** [comment]
> 
> 
> wtf

所以之前给您Pr,您关了我的Pr...

**Comment by KFERMercer** [comment]
额, 看到是针对workflow的就直接关了, 抱歉
