### ISSUE TITLE
老大 把adguardhome集成进去吧

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#24]
adbyby老是更新规则失败，kpr负载太高，adguardhome过滤效果还是不错的

**Comment by KFERMercer** [comment]
adguardhome太重了, 为了过滤广告而使之成为dns上游的代价难以接受, 会出很多问题.

建议用ssrp里的广告过滤功能搭配dnsmasq规则来代替adbyby:

![image](https://user-images.githubusercontent.com/37098748/89704802-ca89d900-d989-11ea-9dc9-75a66dfdea5f.png)
