### ISSUE TITLE
 Make download fail这个怎麽解决啊？

### ISSUE THREAD

**Issue by iamjimmycheng** [KFERMercer/OpenWrt#27]
Make download23s
  shell: /bin/bash -e {0}
Run make download -j8 || make download -j1 V=s
  make download -j8 || make download -j1 V=s
  find ./dl/ -size -1024c -exec rm -f {} \;
  df -h
  shell: /bin/bash -e {0}
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..fd1271bcc965e629028ade8403f1e19674752c54
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..fd1271bcc965e629028ade8403f1e19674752c54
/home/runner/work/lede/lede/.config:4: *** missing separator.  Stop.

/home/runner/work/lede/lede/.config:4: *** missing separator.  Stop.
make[1]: Entering directory '/home/runner/work/lede/lede'
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..fd1271bcc965e629028ade8403f1e19674752c54
make[2]: Entering directory '/home/runner/work/lede/lede/scripts/config'
set -e; mkdir -p ./; trap "rm -f ./.mconf-cfg.tmp" EXIT; { /bin/sh mconf-cfg.sh; } > ./.mconf-cfg.tmp; if [ ! -r mconf-cfg ] || ! cmp -s mconf-cfg ./.mconf-cfg.tmp; then true '  UPD     mconf-cfg'; mv -f ./.mconf-cfg.tmp mconf-cfg; fi
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o mconf.o mconf.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/checklist.o lxdialog/checklist.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/inputbox.o lxdialog/inputbox.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/menubox.o lxdialog/menubox.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/textbox.o lxdialog/textbox.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/util.o lxdialog/util.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/yesno.o lxdialog/yesno.c
cc -o mconf mconf.o lxdialog/checklist.o lxdialog/inputbox.o lxdialog/menubox.o lxdialog/textbox.o lxdialog/util.o lxdialog/yesno.o confdata.o expr.o lexer.lex.o parser.tab.o preprocess.o symbol.o util.o -lncurses -ltinfo
make[2]: Leaving directory '/home/runner/work/lede/lede/scripts/config'
make[2]: Entering directory '/home/runner/work/lede/lede'

**Comment by KFERMercer** [comment]
提供下.config
