### ISSUE TITLE
虚拟机不支持？

### ISSUE THREAD

**Issue by gzxiexl** [KFERMercer/OpenWrt#3]
esxi虚拟机尝试了一下 无法进入系统 麻烦大佬看下

**Comment by gzxiexl** [comment]
我下载的版本是R9.10.24-10.28 build on Oct 28, 2019

**Comment by zlr1** [comment]
你好，你是不是发错对象了？



---原始邮件---
发件人: "gzxiexl"<notifications@github.com&gt;
发送时间: 2019年10月30日(星期三) 中午1:57
收件人: "KFERMercer/OpenWrt"<OpenWrt@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [KFERMercer/OpenWrt] 虚拟机不支持？ (#3)



我下载的版本是R9.10.24-10.28 build on Oct 28, 2019

**Comment by KFERMercer** [comment]
详细描述一下问题？

**Comment by gzxiexl** [comment]
转成vmdk后 在esxi新建一个虚拟机 导入后一直卡住

**Comment by KFERMercer** [comment]
我用VirtualBox测试过是正常的, 关于esxi, 如果你刷入是无限重启的话，可以参见这个问题. https://github.com/coolsnowwolf/lede/issues/1900

**Comment by KFERMercer** [comment]
看了一下commit log, 大雕修复这个问题确实在10.28版本release之后, 建议拉取最新代码重新编译
