### ISSUE TITLE
打印机服务

### ISSUE THREAD

**Issue by wt67451347** [KFERMercer/OpenWrt#30]
没有打印机服务，安装也安装不了，能加上这个服务么？

**Comment by KFERMercer** [comment]
[luci-app-usb-printer](https://github.com/KFERMercer/OpenWrt/tree/master/package/lean/luci-app-usb-printer)

**Comment by KFERMercer** [comment]
https://github.com/KFERMercer/OpenWrt/commit/5f79d8daff04550c297705f740355ae42f333c28
