### ISSUE TITLE
ShadowsocksR Plus+ 运行V2RAY，插件无法运行。

### ISSUE THREAD

**Issue by baodp** [KFERMercer/OpenWrt#32]
ShadowsocksR Plus+ 选择V2RAY服务器，插件无法运行。
日志显示：Main node:Can't find  program, can't start!

固件版本 | OpenWrt R20.12.12 built by Lean & KFERM / LuCI Master (git-20.343.54716-6fc079f)
-- | --

X86

**Comment by KFERMercer** [comment]
下载最新版本. 早期版本有程序路径错误

**Comment by KFERMercer** [comment]
https://github.com/coolsnowwolf/lede/pull/5855
