### ISSUE TITLE
大佬请修复ARP静态绑定问题

### ISSUE THREAD

**Issue by lsx25** [KFERMercer/OpenWrt#34]
IP/MAC绑定后，做好端口转发和动态域名绑定，通过域名可外网唤醒设备，但是设备离线或重启后，arp绑定状态就会失效，外网无法无法唤醒设备，希望大佬能修复这个。

**Comment by KFERMercer** [comment]
arp绑定且设备离线后重新上线, IP地址会变吗? 开启flowoffload或者SFE转发加速了吗?

**Comment by lsx25** [comment]
ip地址不变，arp绑定以后，用arp命令查询显示是0x6，一旦设备重启，就会变成0x2

**Comment by lsx25** [comment]
> arp绑定且设备离线后重新上线，IP地址会变吗？开启flowoffload或者SFE转发加速了吗？

![20210302091026](https://user-images.githubusercontent.com/80080423/110201470-34c21800-7e9e-11eb-8602-4c5b38221f17.png)
这个是设置绑定后重启路由器的状态，
![20210302091108](https://user-images.githubusercontent.com/80080423/110201486-4acfd880-7e9e-11eb-86a0-ab91f30f2c15.png)
这个是设备重启后，或者重新接入网络的状态，
每次设备重启都会失去绑定的静态arp，导致远程唤醒失效

**Comment by KFERMercer** [comment]
我怀疑是udp转发出现了问题.

仅仅从arp条目上看, 似乎一切正常.  实际上, openwrt本来就会倾向给同样的mac地址分配同样的ip, 所以即使在不进行arp的情况下, 端口映射一般而言也会正常工作.

几个问题:

如果删除此条arp条目, 直接对192.168.5.5进行端口转发, 设备重启后会正常工作吗?

你是否在固件里编译了docker?

你是否正在使用flowoffload或者SFE转发加速?

由于我还没能复现你所说的问题, 建议同时去冷雪狼的库下面提交讨论看有没有人遇到了同样的问题.

**Comment by lsx25** [comment]
应该不能算正常静态arp吧，应该显示0x6才是正确的，用ip neigh show命令显示192.168.5.5 dev br-lan lladdr 00:11:32:8b:90:e7 PERMANENT，有PERMANENT才是静态arp，重启以后这个状态就没了，感觉是每次设备接入网络，静态arp就被清理了。
我是J3455CPU，82576的网卡，四个网口一个做wan，其他四个设置为LAN，打开桥接。

**Comment by KFERMercer** [comment]
根据: https://github.com/coolsnowwolf/lede/issues/6384
提交: https://github.com/KFERMercer/OpenWrt/commit/c35b1eb38b5446c59625282bad0af33d72f8ba23

欢迎测试

**Comment by lsx25** [comment]
测试了一下，是这样，上图吧
群晖关机或重启前,设置IP/mac绑定
![绑定-重启前](https://user-images.githubusercontent.com/80080423/110277202-c1401800-800f-11eb-926e-5b368e38ff9b.jpg)
![设备重启前](https://user-images.githubusercontent.com/80080423/110277222-cb621680-800f-11eb-9aad-5eb534a5c697.jpg)
群晖重启
![重启后](https://user-images.githubusercontent.com/80080423/110277254-d87f0580-800f-11eb-9380-dfb6a4431472.jpg)
![重启后1](https://user-images.githubusercontent.com/80080423/110277270-dcab2300-800f-11eb-9357-ed96b6dfed48.jpg)
重启后关机
![关机arp](https://user-images.githubusercontent.com/80080423/110277295-e6348b00-800f-11eb-8d7d-02aac5a8860a.jpg)
![关机ip show](https://user-images.githubusercontent.com/80080423/110277299-e92f7b80-800f-11eb-8cf7-23cb06625bb1.jpg)

**Comment by KFERMercer** [comment]
1. 其他设备会出现上述唤醒问题吗?
2. 在群晖关机后, 在内网内使用luci-app-wol通过群晖的mac地址可以唤醒吗?
3. 在不绑定arp的情况下, 群晖重启后dhcp的租约会刷新吗?
4. 在群晖关机的情况下, 使用`arp -s 192.168.5.5 xx:xx:xx:xx:xx:xx`添加arp配置后的状态码是什么?

**Comment by lsx25** [comment]
所有设备都存在这个问题，也和别人沟通过也是一样。
内网可以唤醒。
我设置了静态ip，和arp静态地址是一样的。
arp -s命令不能用，后面参数都是查询
