### ISSUE TITLE
baidupcs-web-3.7.3编译失败

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#35]
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-rt2800-lib_installed
echo "kmod-rt2800-lib" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/mac80211.default.install
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/backports-5.8.18-1/.pkgdir/kmod-rt2800-usb/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-rt2800-usb_installed
echo "kmod-rt2800-usb" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/mac80211.default.install
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
echo '5.8.18-1-3' | cmp -s - /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/kmod-cfg80211.version || echo '5.8.18-1-3' > /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/kmod-cfg80211.version
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/backports-5.8.18-1/.pkgdir/kmod-cfg80211/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-cfg80211_installed
echo "kmod-cfg80211" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/mac80211.default.install
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
echo '5.8.18-1-3' | cmp -s - /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/kmod-mac80211.version || echo '5.8.18-1-3' > /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/kmod-mac80211.version
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/backports-5.8.18-1/.pkgdir/kmod-mac80211/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-mac80211_installed
echo "kmod-mac80211" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/mac80211.default.install
make[3]: Leaving directory '/workdir/openwrt/package/kernel/mac80211'
time: package/kernel/mac80211/compile#151.53#19.35#170.85
make[3]: Entering directory '/workdir/openwrt/package/kferm/baidupcs-web'
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.built
touch /workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.built_check
( GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) go get -v github.com/GeertJohan/go.rice/rice/... ; cd /workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/internal/pcsweb ; "$(go env GOPATH)/bin/rice" embed-go ; )
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/workdir/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/workdir/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/Erope/BaiduPCS-Go" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/Erope/BaiduPCS-Go/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3" GO_BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.go_work/build" GO_BUILD_BIN_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/workdir/openwrt/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOARM="" GOMIPS="" GOMIPS64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3=baidupcs-web-3.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/workdir/openwrt/staging_dir/target-x86_64_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3=baidupcs-web-3.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/workdir/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/workdir/openwrt/staging_dir/target-x86_64_musl/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.go_work/build" GOCACHE="/workdir/openwrt/tmp/go-build" GOMODCACHE="/workdir/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /workdir/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1617392318' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/workdir/openwrt/staging_dir/target-x86_64_musl/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-s -w -X main.Version=v3.7.3 -buildid '1617392318' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/workdir/openwrt/staging_dir/target-x86_64_musl/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

Building targets
../../pcsutil/jwted25519/jwted25519.go:4:2: missing go.sum entry for module providing package github.com/dgrijalva/jwt-go (imported by github.com/Erope/BaiduPCS-Go/pcsutil/jwted25519); to add:
	go get github.com/Erope/BaiduPCS-Go/pcsutil/jwted25519
../../pcsutil/jwted25519/jwted25519.go:5:2: missing go.sum entry for module providing package golang.org/x/crypto/ed25519 (imported by github.com/Erope/BaiduPCS-Go/pcsutil/jwted25519); to add:
	go get github.com/Erope/BaiduPCS-Go/pcsutil/jwted25519

make[3]: *** [/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.built] Error 1
Makefile:63: recipe for target '/workdir/openwrt/build_dir/target-x86_64_musl/baidupcs-web-3.7.3/.built' failed
make[3]: Leaving directory '/workdir/openwrt/package/kferm/baidupcs-web'
time: package/kferm/baidupcs-web/compile#1.01#0.31#1.31
package/Makefile:111: recipe for target 'package/kferm/baidupcs-web/compile' failed
make[2]: *** [package/kferm/baidupcs-web/compile] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make: *** [world] Error 2
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
Error: Process completed with exit code 2.

**Comment by KFERMercer** [comment]
已修复: cf194340bef4651945762e28d121ef531dff5df7
