### ISSUE TITLE
主题  Argon 登陆页面打开慢

### ISSUE THREAD

**Issue by baodp** [KFERMercer/OpenWrt#40]
主题  Argon 登陆页面打开要等好几秒，其他主题不会。
是不是因为登陆要打开 （下载）图片的原因？
有办法改进吗？？？
谢谢。

**Comment by KFERMercer** [comment]
https://github.com/KFERMercer/OpenWrt/commit/b6f034494b57008fa7eccc97bc9028cd33a645c2
↑ 已修复
