### ISSUE TITLE
最新编译后无法升级

### ISSUE THREAD

**Issue by jh0072110** [KFERMercer/OpenWrt#5]
大佬，用最新代码编译后刷入软路由，会出现两个问题：
1.不管选不选保留配置都会重置。
2.刷入以后（是以后）web界面和ssh界面的sysupgrade全部挂掉了，没法再次刷机😥

**Comment by KFERMercer** [comment]
几天前升级了base-files, 还没有测试. 看来有问题. 谢谢反馈.

**Comment by KFERMercer** [comment]
暂时恢复了.
