### ISSUE TITLE
luci-app-dockerman: 容器选择bridge，不能访问外网

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#6]
luci-app-dockerman: 容器选择bridge，不能访问外网

**Comment by KFERMercer** [comment]
这个插件我还没测试过, 不过看dockerman的库里有人出现过这个问题: https://github.com/lisaac/luci-app-dockerman/issues/6, 具体情况要等到我测试过才能解答.

另外调查一下, 其他的功能正常运行吗? 显示有错误吗? 可否提供一下插件界面截图?

**Comment by tcsr200722** [comment]
其他功能正常，没有显示运行错误

**Comment by tcsr200722** [comment]
这个是lisaac的回复    今天有空接触了一下 lean 的 lede
可能是应该 docker-ce 的 bug，也有可能是 docker-ce 和其他插件的一些冲突，导致 iptable 中没有开启 SNAT， 通过这条命令可以修复

iptables -t nat -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
具体原因就不查了

**Comment by tcsr200722** [comment]
经过测试选择luci-app-docker编译也同样不能链接外网，所以应该是固件本身的原因
