### ISSUE TITLE
更新代码后ServerChan失效，无法启动

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#7]
Tue Feb 25 19:03:16 2020 kern.warn kernel: [22411.438238] [2] 10.10.10.8 visit 1003, time=1582628596 action=Accept, 0/4
Tue Feb 25 19:03:29 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:03:40 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:03:40 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:03:46 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:03:47 2020 daemon.err nmbd[5912]: [2020/02/25 19:03:47.000441,  0] ../../source3/nmbd/nmbd.c:59(terminate)
Tue Feb 25 19:03:47 2020 daemon.err nmbd[5912]:   Got SIGTERM: going down...
Tue Feb 25 19:03:48 2020 daemon.err nmbd[11454]: [2020/02/25 19:03:48.203261,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
Tue Feb 25 19:03:48 2020 daemon.err nmbd[11454]:   daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
Tue Feb 25 19:03:48 2020 daemon.err smbd[11453]: [2020/02/25 19:03:48.230631,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
Tue Feb 25 19:03:48 2020 daemon.err smbd[11453]:   daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
Tue Feb 25 19:04:11 2020 daemon.err nmbd[11454]: [2020/02/25 19:04:11.228184,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
Tue Feb 25 19:04:11 2020 daemon.err nmbd[11454]:   *****
Tue Feb 25 19:04:11 2020 daemon.err nmbd[11454]:
Tue Feb 25 19:04:11 2020 daemon.err nmbd[11454]:   Samba name server OPENWRT is now a local master browser for workgroup WORKGROUP on subnet 10.10.10.1
Tue Feb 25 19:04:11 2020 daemon.err nmbd[11454]:
Tue Feb 25 19:04:11 2020 daemon.err nmbd[11454]:   *****
Tue Feb 25 19:04:12 2020 daemon.err uhttpd[3764]: sh: /etc/init.d/serverchan: Permission denied
Tue Feb 25 19:05:52 2020 kern.warn kernel: [22566.815407] __af_update_client_app_info 727 visit_app_num = 0
Tue Feb 25 19:05:52 2020 kern.warn kernel: [22566.815615] [2] 10.10.10.4 visit 3001, time=1582628751 action=Accept, 0/15
Tue Feb 25 19:07:22 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:07:28 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:07:28 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:07:42 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:07:48 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied
Tue Feb 25 19:07:48 2020 daemon.err uhttpd[3764]: sh: /etc/init.d/serverchan: Permission denied
Tue Feb 25 19:07:56 2020 daemon.err uhttpd[3764]: env: can't execute '/etc/init.d/serverchan': Permission denied

**Comment by KFERMercer** [comment]
修复.

**Comment by KFERMercer** [comment]
修复.
