### ISSUE TITLE
ServerChan没有修复

### ISSUE THREAD

**Issue by tcsr200722** [KFERMercer/OpenWrt#8]
Wed Feb 26 16:34:02 2020 daemon.err uhttpd[2947]: sh: /etc/init.d/serverchan: Permission denied
Wed Feb 26 16:34:13 2020 daemon.err uhttpd[2947]: env: can't execute '/etc/init.d/serverchan': Permission denied
Wed Feb 26 16:34:20 2020 daemon.err uhttpd[2947]: env: can't execute '/etc/init.d/serverchan': Permission denied
Wed Feb 26 16:34:20 2020 daemon.err uhttpd[2947]: env: can't execute '/etc/init.d/serverchan': Permission denied

**Comment by KFERMercer** [comment]
chmod 755 /etc/init.d/serverchan
或者重新编译
